modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "colored_packages"
version = "${version}"
displayName = "Create: Colored Packages"
authors = "TimmyChips"
description = '''
Adds several colored packages from applying dye to the Create: Packager block
'''
#logoFile = ""

[[dependencies.colored_packages]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colored_packages]]
modId = "minecraft"
type="required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colored_packages]]
modId = "architectury"
type="required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.colored_packages]]
modId = "create"
type="required"
versionRange="[6.0.9,6.1.0)"
ordering = "BEFORE"
side = "BOTH"

[[mixins]]
config = "colored_packages.mixins.json"